primitive_topology = "Triangle"

[rasterizer]
fill_mode = "Solid"
cull_mode = "Back"
front_counter_clockwise = false
depth_bias = 0
depth_bias_clamp = 0.0
slope_scaled_depth_bias = 0.0
depth_clip_enable = true
conservative_raster = false

[depth_stencil]
depth_enable = false
depth_write_mask = "All"
depth_func = "LessEqual"
stencil_enable = false
stencil_read_mask = 255
stencil_write_mask = 255

[depth_stencil.front_face]
stencil_fail_op = "Keep"
stencil_depth_fail_op = "Keep"
stencil_pass_op = "Keep"
stencil_func = "Always"

[depth_stencil.back_face]
stencil_fail_op = "Keep"
stencil_depth_fail_op = "Keep"
stencil_pass_op = "Keep"
stencil_func = "Always"

[blend]
alpha_to_coverage_enable = false
independent_blend_enable = false

[[blend.rtblends]]
blend_enable = false
src_blend = "One"
dst_blend = "Zero"
blend_op = "Add"
src_blend_alpha = "One"
dst_blend_alpha = "Zero"
blend_op_alpha = "Add"
render_target_write_mask = 15